spring:
  config:
    import: env.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://localhost:5433/${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  server:
      port: 8082